### ISSUE TITLE
Override color information from spreadsheets

### ISSUE THREAD

**Issue by yodaXX** [hoogi91/charts#1]
Hi, great Extension.

It would be cool to change the colors of the chart without messing with the spreadsheet itself.
Something like a colormatrix override.

I tried it by extending the ChartDataSpreadsheet model with a custom colormatrix field and used the table input TCA feature.

Background;Border

Instead of assigning the color information from the cells, the color matrix is read first.

![image](https://user-images.githubusercontent.com/13272160/51920733-43e45b00-23e6-11e9-9d10-9281b14864c5.png)

**Comment by hoogi91** [comment]
Hi @yodaXX,

thx for your request and possible solution. I agree that the extension should support such an option so that editors would be able to select the colors by themselve.

While developing this extension i was thinking of a dataset preview as a chart where the coloring will be shown. Maybe it would be possible to add colorpickers at this point to generate such a matrix. With that handling it could be also possible for normal editors/integrators to set coloring on charts.

It would be great if you could start a feature branch in a fork of this repository with your changes so that we can start a discussion on it. Hopefully i will find some time in the next days/weeks to get into work on that topic :D

Thanks & best Regards 😃

**Comment by sulman8s** [comment]
Hey, 

I am currently using the standard way to add the dataset (not using spreadsheets). It would be nice and possible if it is available as general inside the extension. Thanks,

Best regards,
Suleman

**Comment by hoogi91** [comment]
Finally [v2](https://github.com/hoogi91/charts/releases/tag/2.0.0) is out now! And with that version I added a color picker component to define custom colors for background and borders.
See the [docs](https://docs.typo3.org/p/hoogi91/charts/main/en-us/Editor/Index.html#chart-dataset) on how to add such a color palette. The picker should be self-explained but and looks like described in https://docs.typo3.org/p/hoogi91/charts/main/en-us/Editor/Index.html#color-palette-editor

<img width="300" src="https://docs.typo3.org/p/hoogi91/charts/main/en-us/_images/dataset-colors.png"/>
<img width="300" src="https://docs.typo3.org/p/hoogi91/charts/main/en-us/_images/color-palette.png"/>
<img width="300" src="https://docs.typo3.org/p/hoogi91/charts/main/en-us/_images/color-picker.png"/>
