### ISSUE TITLE
Backend preview cannot be rendered with PHP 8(.1)

### ISSUE THREAD

**Issue by TheNaderio** [hoogi91/charts#176]
**Version(s) affected**: 
2.0.6

**Description**  
<img width="955" alt="image" src="https://user-images.githubusercontent.com/25088164/220065819-3f20e768-bf41-4724-80d6-4be57c7e48e5.png">

**How to reproduce**  

1. `composer require hoogi91/charts --no-dev`
2. Create diagram data
3. create chart content element (line, bar, ... doesn't care)
4. open page in site-view

**Possible Solution**  

Update code to be PHP >8 compatible

**Additional context**  
If installed without `--no-dev`, the "spreadsheets" extension will be installed and you cannot even create the diagram-data record due to PHP 8 errors

**Comment by hoogi91** [comment]
Hey @TheNaderio,

thanks for your report. I updated the required PHP version in latest release [3.0.0](https://github.com/hoogi91/charts/releases/tag/3.0.0) and also upgraded the code to be compatible with PHP >8.1.

Due to the fact that the issue was only visible when PHP's error reporting was considering deprecations I just fixed it for newer version. If you are already on TYPO3 v11 you should be able to simply upgrade to v3 of this library 😄
