### ISSUE TITLE
ColorPicker not working on Firefox

### ISSUE THREAD

**Issue by Acconitum** [hoogi91/charts#25]
**Version(s) affected**: 2.0.0

**Description**  
Firefox V 97.0 (64-Bit) triggers function not found exceptions in javascript console when accessing the modal

**How to reproduce**  
- Start firefox
- Open a dataset from Listview
- Try to use the colorpicker

**Possible Solution**  
Seems like firefox is not interpreting JavaScript arrow functions correctly and does not maintain the overlaying JavaScript Class as "this" inside eventlistener callbacks. bind(this) could be a solution but requires a lot of code refactoring.

**Additional context**  
There is another small issue around the colorpicker. If you created a new palette, the palette would show up in the backend. The element which holds and displays the color as a bar, has a height of 32px which is ignored due to the elements inline nature. Add display: block as additional css rule (Classes/Form/Element/ColorPaletteInputElement.php line 47) to display the bar as desired.

**Comment by hoogi91** [comment]
Hey @Acconitum,

please check again, the issue was related to the following Firefox Issue https://bugzilla.mozilla.org/show_bug.cgi?id=1502814
The creation of custom elements was done before adding them to the DOM. When the element was added to the DOM via "append" method the prototype got changed and all methods were not available... 
The recommended workaround solved the issues for now :)

Just checkout the fix version 2.0.1 and give me some feedback if it fixes your issue :)

**Comment by hoogi91** [comment]
Hey @Acconitum,

I just released [2.0.5](https://github.com/hoogi91/charts/releases/tag/2.0.5) which should contain all relevant fixes to have an equal view of the color palette/preview across browsers and TYPO3 versions :)

Best Regards

**Comment by Acconitum** [comment]
Hey @hoogi91 
Works perfectly! Thanks a lot!
I apologize for the failed tests! It is finally time for me to dive deep into unittests. This will prevent me from thinking "My change can't break any tests", which is just naive.
