### ISSUE TITLE
Class Hoogi91\Spreadsheets\Service\ExtractorService does not exist

### ISSUE THREAD

**Issue by rtoenjes** [hoogi91/charts#30]
**Version(s) affected**: 2.0.5
TYPO3 10.4.27

**Description**  
After doing a fresh installation, adding a simple dataset and adding a plugin with this data in backend, I get a `Class Hoogi91\Spreadsheets\Service\ExtractorService does not exist. Reflection failed.` in BE and FE.

**Possible Solution**  
The installation of EXT:spreadsheet does help. But as I understand the documentation, it is not mandatory to install EXT:spreadsheet.

**Comment by hoogi91** [comment]
Hey @rtoenjes,

thanks for your PR. Please have a look into release [2.0.6](https://github.com/hoogi91/charts/releases/tag/2.0.6) as this version should fix the issue. The problem seems to be extbase which is loading class references from configuration via reflection and thus also tries to inject the dependencies.... I adapted the configuration part to first check if spreadsheets extension is availalbe or not before applying the relevant configuration and it seems to fix the problem on my machine.

Hope it also helps on your installation. If not don't hesitate and let me know. Cheers 🍻
